name: Deployment
on:
  push:
    branches: [production]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install dependencies
        run: |
          npm install

      - name: Build
        run: npm run build

      - name: Sync
        env:
          dest: ${{secrets.DEST_PATH}}
          port: ${{secrets.SERVER_PORT}}
          key: ${{secrets.DEPLOY_KEY}}
        run: |
          echo "${{env.key}}" > deploy_key
          chmod 600 ./deploy_key
          rsync -chav --delete \
            -e 'ssh -p ${{env.port}} -i ./deploy_key -o StrictHostKeyChecking=no' \
            --exclude /deploy_key \
            --exclude /.git/ \
            --exclude /.github/ \
            --exclude /node_modules/ \
            ./ ${{env.dest}}
